bugfixes

diff --git a/.github/workflows/next.CI-CD.yml b/.github/workflows/next.CI-CD.yml
--- a/.github/workflows/next.CI-CD.yml
+++ b/.github/workflows/next.CI-CD.yml
@@ -103,13 +103,48 @@ jobs:
       BUILD_MODE: "standalone"
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      # CHECKOUT
+      - name: Checkout
         uses: actions/checkout@v4
-
+      # Detect package manager
+      - name: Detect package manager
+        id: detect-package-manager
+        working-directory: ./app
+        run: |
+          if [ -f "${{ github.workspace }}/app/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/app/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=i" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      # INSTALL NODE
       - name: Install Node.js
         uses: actions/setup-node@v4
         with:
           node-version: "20.12.x"
+      # RESTORE CACHE
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            app/.next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      # INSTALL DEPENDENCIES
+      - name: Install dependencies
+        working-directory: ./app
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
       # LOAD CUSTOM ENV VARIABLES
       - name: Create .env.local File
         working-directory: ./app
